// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/auth/forgot-password.tsx";
import * as $1 from "./routes/auth/index.tsx";
import * as $2 from "./routes/auth/login.tsx";
import * as $3 from "./routes/auth/signup.tsx";
import * as $4 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/auth/forgot-password.tsx": $0,
    "./routes/auth/index.tsx": $1,
    "./routes/auth/login.tsx": $2,
    "./routes/auth/signup.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
