// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[plantId].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/admin/customers/index.tsx";
import * as $6 from "./routes/admin/index.tsx";
import * as $7 from "./routes/admin/plants/create.tsx";
import * as $8 from "./routes/admin/plants/index.tsx";
import * as $9 from "./routes/api/file-stream.ts";
import * as $10 from "./routes/auth/forgot-password.tsx";
import * as $11 from "./routes/auth/index.tsx";
import * as $12 from "./routes/auth/signup.tsx";
import * as $13 from "./routes/auth/verify-otp.tsx";
import * as $14 from "./routes/index.tsx";
import * as $$0 from "./islands/EditPlantModal.tsx";
import * as $$1 from "./islands/ImageUpload.tsx";

const manifest = {
  routes: {
    "./routes/[plantId].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/admin/customers/index.tsx": $5,
    "./routes/admin/index.tsx": $6,
    "./routes/admin/plants/create.tsx": $7,
    "./routes/admin/plants/index.tsx": $8,
    "./routes/api/file-stream.ts": $9,
    "./routes/auth/forgot-password.tsx": $10,
    "./routes/auth/index.tsx": $11,
    "./routes/auth/signup.tsx": $12,
    "./routes/auth/verify-otp.tsx": $13,
    "./routes/index.tsx": $14,
  },
  islands: {
    "./islands/EditPlantModal.tsx": $$0,
    "./islands/ImageUpload.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
